/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package dwg.climber.oil_climber;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public class SimilarImg implements org.apache.thrift.TBase<SimilarImg, SimilarImg._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimilarImg");

  private static final org.apache.thrift.protocol.TField IMG_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("imgUrl", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LINK_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("linkUrl", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SimilarImgStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SimilarImgTupleSchemeFactory());
  }

  public String imgUrl; // required
  public String linkUrl; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMG_URL((short)1, "imgUrl"),
    LINK_URL((short)2, "linkUrl");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMG_URL
          return IMG_URL;
        case 2: // LINK_URL
          return LINK_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMG_URL, new org.apache.thrift.meta_data.FieldMetaData("imgUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LINK_URL, new org.apache.thrift.meta_data.FieldMetaData("linkUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimilarImg.class, metaDataMap);
  }

  public SimilarImg() {
  }

  public SimilarImg(
    String imgUrl,
    String linkUrl)
  {
    this();
    this.imgUrl = imgUrl;
    this.linkUrl = linkUrl;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SimilarImg(SimilarImg other) {
    if (other.isSetImgUrl()) {
      this.imgUrl = other.imgUrl;
    }
    if (other.isSetLinkUrl()) {
      this.linkUrl = other.linkUrl;
    }
  }

  public SimilarImg deepCopy() {
    return new SimilarImg(this);
  }

  @Override
  public void clear() {
    this.imgUrl = null;
    this.linkUrl = null;
  }

  public String getImgUrl() {
    return this.imgUrl;
  }

  public SimilarImg setImgUrl(String imgUrl) {
    this.imgUrl = imgUrl;
    return this;
  }

  public void unsetImgUrl() {
    this.imgUrl = null;
  }

  /** Returns true if field imgUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetImgUrl() {
    return this.imgUrl != null;
  }

  public void setImgUrlIsSet(boolean value) {
    if (!value) {
      this.imgUrl = null;
    }
  }

  public String getLinkUrl() {
    return this.linkUrl;
  }

  public SimilarImg setLinkUrl(String linkUrl) {
    this.linkUrl = linkUrl;
    return this;
  }

  public void unsetLinkUrl() {
    this.linkUrl = null;
  }

  /** Returns true if field linkUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetLinkUrl() {
    return this.linkUrl != null;
  }

  public void setLinkUrlIsSet(boolean value) {
    if (!value) {
      this.linkUrl = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IMG_URL:
      if (value == null) {
        unsetImgUrl();
      } else {
        setImgUrl((String)value);
      }
      break;

    case LINK_URL:
      if (value == null) {
        unsetLinkUrl();
      } else {
        setLinkUrl((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IMG_URL:
      return getImgUrl();

    case LINK_URL:
      return getLinkUrl();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IMG_URL:
      return isSetImgUrl();
    case LINK_URL:
      return isSetLinkUrl();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SimilarImg)
      return this.equals((SimilarImg)that);
    return false;
  }

  public boolean equals(SimilarImg that) {
    if (that == null)
      return false;

    boolean this_present_imgUrl = true && this.isSetImgUrl();
    boolean that_present_imgUrl = true && that.isSetImgUrl();
    if (this_present_imgUrl || that_present_imgUrl) {
      if (!(this_present_imgUrl && that_present_imgUrl))
        return false;
      if (!this.imgUrl.equals(that.imgUrl))
        return false;
    }

    boolean this_present_linkUrl = true && this.isSetLinkUrl();
    boolean that_present_linkUrl = true && that.isSetLinkUrl();
    if (this_present_linkUrl || that_present_linkUrl) {
      if (!(this_present_linkUrl && that_present_linkUrl))
        return false;
      if (!this.linkUrl.equals(that.linkUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(SimilarImg other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SimilarImg typedOther = (SimilarImg)other;

    lastComparison = Boolean.valueOf(isSetImgUrl()).compareTo(typedOther.isSetImgUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImgUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imgUrl, typedOther.imgUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLinkUrl()).compareTo(typedOther.isSetLinkUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLinkUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.linkUrl, typedOther.linkUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SimilarImg(");
    boolean first = true;

    sb.append("imgUrl:");
    if (this.imgUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.imgUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("linkUrl:");
    if (this.linkUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.linkUrl);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SimilarImgStandardSchemeFactory implements SchemeFactory {
    public SimilarImgStandardScheme getScheme() {
      return new SimilarImgStandardScheme();
    }
  }

  private static class SimilarImgStandardScheme extends StandardScheme<SimilarImg> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SimilarImg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMG_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imgUrl = iprot.readString();
              struct.setImgUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LINK_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.linkUrl = iprot.readString();
              struct.setLinkUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SimilarImg struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.imgUrl != null) {
        oprot.writeFieldBegin(IMG_URL_FIELD_DESC);
        oprot.writeString(struct.imgUrl);
        oprot.writeFieldEnd();
      }
      if (struct.linkUrl != null) {
        oprot.writeFieldBegin(LINK_URL_FIELD_DESC);
        oprot.writeString(struct.linkUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SimilarImgTupleSchemeFactory implements SchemeFactory {
    public SimilarImgTupleScheme getScheme() {
      return new SimilarImgTupleScheme();
    }
  }

  private static class SimilarImgTupleScheme extends TupleScheme<SimilarImg> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SimilarImg struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetImgUrl()) {
        optionals.set(0);
      }
      if (struct.isSetLinkUrl()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetImgUrl()) {
        oprot.writeString(struct.imgUrl);
      }
      if (struct.isSetLinkUrl()) {
        oprot.writeString(struct.linkUrl);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SimilarImg struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.imgUrl = iprot.readString();
        struct.setImgUrlIsSet(true);
      }
      if (incoming.get(1)) {
        struct.linkUrl = iprot.readString();
        struct.setLinkUrlIsSet(true);
      }
    }
  }

}

